/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as QuizConfigSessionIdRouteImport } from './routes/quiz-config.$sessionId'
import { Route as QuizConfigIdRouteImport } from './routes/quiz-config.$id'
import { Route as ContentIdRouteImport } from './routes/content.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizConfigSessionIdRoute = QuizConfigSessionIdRouteImport.update({
  id: '/quiz-config/$sessionId',
  path: '/quiz-config/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizConfigIdRoute = QuizConfigIdRouteImport.update({
  id: '/quiz-config/$id',
  path: '/quiz-config/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentIdRoute = ContentIdRouteImport.update({
  id: '/content/$id',
  path: '/content/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/flashcards': typeof FlashcardsRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/content/$id': typeof ContentIdRoute
  '/quiz-config/$id': typeof QuizConfigIdRoute
  '/quiz-config/$sessionId': typeof QuizConfigSessionIdRoute
  '/auth/': typeof AuthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/flashcards': typeof FlashcardsRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/content/$id': typeof ContentIdRoute
  '/quiz-config/$id': typeof QuizConfigIdRoute
  '/quiz-config/$sessionId': typeof QuizConfigSessionIdRoute
  '/auth': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/flashcards': typeof FlashcardsRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/content/$id': typeof ContentIdRoute
  '/quiz-config/$id': typeof QuizConfigIdRoute
  '/quiz-config/$sessionId': typeof QuizConfigSessionIdRoute
  '/auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/flashcards'
    | '/profile'
    | '/saved'
    | '/settings'
    | '/auth/callback'
    | '/content/$id'
    | '/quiz-config/$id'
    | '/quiz-config/$sessionId'
    | '/auth/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/flashcards'
    | '/profile'
    | '/saved'
    | '/settings'
    | '/auth/callback'
    | '/content/$id'
    | '/quiz-config/$id'
    | '/quiz-config/$sessionId'
    | '/auth'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/flashcards'
    | '/profile'
    | '/saved'
    | '/settings'
    | '/auth/callback'
    | '/content/$id'
    | '/quiz-config/$id'
    | '/quiz-config/$sessionId'
    | '/auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FlashcardsRoute: typeof FlashcardsRoute
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ContentIdRoute: typeof ContentIdRoute
  QuizConfigIdRoute: typeof QuizConfigIdRoute
  QuizConfigSessionIdRoute: typeof QuizConfigSessionIdRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz-config/$sessionId': {
      id: '/quiz-config/$sessionId'
      path: '/quiz-config/$sessionId'
      fullPath: '/quiz-config/$sessionId'
      preLoaderRoute: typeof QuizConfigSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz-config/$id': {
      id: '/quiz-config/$id'
      path: '/quiz-config/$id'
      fullPath: '/quiz-config/$id'
      preLoaderRoute: typeof QuizConfigIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$id': {
      id: '/content/$id'
      path: '/content/$id'
      fullPath: '/content/$id'
      preLoaderRoute: typeof ContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FlashcardsRoute: FlashcardsRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ContentIdRoute: ContentIdRoute,
  QuizConfigIdRoute: QuizConfigIdRoute,
  QuizConfigSessionIdRoute: QuizConfigSessionIdRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
